#IF(POLICY CMP0048)
#  CMAKE_POLICY(SET CMP0048 OLD)
#ENDIF(POLICY CMP0048)

cmake -DLEMON_ENABLE_SOPLEX=NO -DLEMON_ENABLE_COIN=NO -DLEMON_ENABLE_ILOG=NO -DCMAKE_INSTALL_PREFIX=$HOME/Cloud/GitHub/wireless/LPwirelessCapacity/library/
